#!/bin/bash

while true
do

# Logo

echo "============================================================"
curl -s https://raw.githubusercontent.com/nodersteam/script/main/Noders.sh | bash
echo "============================================================"


PS3='Select an action: '
options=(
"Setup parametrs" 
"Start bot"
"Exit")
select opt in "${options[@]}"
               do
                   case $opt in
                   
"Setup parametrs")

#PARAM TG
echo "============================================================"
echo "Setup your node name"
echo "============================================================"
read NODENAME
echo export NODENAME=${NODENAME} >> $HOME/.bash_profile
echo "============================================================"
echo "Setup your API"
echo "============================================================"
read TG_API
echo export TG_API=${TG_API} >> $HOME/.bash_profile
echo "============================================================"
echo "Setup your Chat ID"
echo "============================================================"
read TG_ID
echo export TG_ID=${TG_ID} >> $HOME/.bash_profile

#PARAM FOR PROJECT
echo "============================================================"
echo "Setup service of project, example - umeed"
echo "============================================================"
read PROJECT
echo export PROJECT=${PROJECT} >> $HOME/.bash_profile
echo "============================================================"
echo "Setup your wallet name"
echo "============================================================"
read WALLETNAME
echo export WALLETNAME=${WALLETNAME} >> $HOME/.bash_profile
echo "============================================================"
echo "Setup your password of wallet"
echo "============================================================"
read PWDDD
echo export PWDDD=${PWDDD} >> $HOME/.bash_profile
echo "============================================================"
echo "Setup denom of token, example - uumee"
echo "============================================================"
read DENOM
echo export DENOM=${DENOM} >> $HOME/.bash_profile
echo "============================================================"
echo "Setup your chain id, example - umee-1"
echo "============================================================"
read CHAIN_ID
echo export CHAIN_ID=${CHAIN_ID} >> $HOME/.bash_profile
echo export DELAY=120 >> $HOME/.bash_profile
source $HOME/.bash_profile

mkdir $HOME/tgbotjail
wget -O $HOME/tgbotjail/start.sh https://raw.githubusercontent.com/nodersteam/cosmostestnet/main/tgbotjail/start.sh
chmod +x $HOME/tgbotjail/start.sh
break
;;
            
"Start bot")
echo "============================================================"
echo "Bot strating"
echo "============================================================"

crontab -e

break
;;

"Exit")
exit
;;

*) echo "invalid option $REPLY";;
esac
done
done
